name: Generate ASCII Artwork - 2

on: push

jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay Program
        run: sudo apt-get install -y cowsay

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

      - name: List repo files
        run: ls -lrta

      - name: Sleep for 30 seconds
        run: sleep 30

    test_job_2:
      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: Sleep for 10 seconds
        run: sleep 10

      - name: List repo files
        run: ls -lrta

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

    deploy_job_3:
      needs: test_job_2
      runs-on: ubuntu-latest
      steps:
      - name: List repo files
        run: ls -lrta
        
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying...
      